services:
  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    entrypoint: ["sh", "-c", "bundle exec rake assets:precompile && exec ./bin/rails server -b 0.0.0.0 -p 3000"]
    volumes:
      - .:/rails
    ports:
      - "5000:3000"
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: ${DATABASE_URL}
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
