default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "enjoy_word_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "enjoy_word_test" } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
